packages:
  - packages/*

catalog:
  '@nuxt/kit': ^4.1.1
  '@nuxt/schema': ^4.1.1
  '@nuxt/ui': ^3.3.3
  '@types/node': ^24.3.1
  nuxt: ^4.1.1
  typescript: ^5.9.2
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-tsc: ^3.0.6
