import { sqliteTable, text } from 'drizzle-orm/sqlite-core'
import { beforeEach, describe, expect, it, vi } from 'vitest'

const todos = sqliteTable('todos', {
  id: text('id').primaryKey(),
  text: text('text'),
})

const autoTodos = sqliteTable('autoTodos', {
  id: text('id').primaryKey(),
  text: text('text'),
})

interface FakeDbOptions {
  /** Error the insert rejects with, if any. */
  insertError?: unknown
  /** Rows the existence probe finds. */
  existing?: any[]
  /** Error the existence probe rejects with, if any. */
  probeError?: unknown
}

/**
 * Minimal stand-in for a drizzle database exposing only the two chains
 * `drizzleCreate` walks: `insert().values().returning()` and
 * `select().from().where().limit()`. Records every probe so tests can assert
 * the happy path performs none.
 */
function createFakeDb({ insertError, existing = [], probeError }: FakeDbOptions) {
  const probes: any[] = []
  return {
    probes,
    insert: () => ({
      values: () => ({
        returning: () => insertError ? Promise.reject(insertError) : Promise.resolve([{ id: 'a', text: 'a' }]),
      }),
    }),
    select: () => ({
      from: () => ({
        where: (condition: any) => {
          probes.push(condition)
          return {
            limit: () => probeError ? Promise.reject(probeError) : Promise.resolve(existing),
          }
        },
      }),
    }),
  }
}

let db: ReturnType<typeof createFakeDb>

vi.mock('$rstore-drizzle-server-utils.js', () => ({
  dialect: 'sqlite',
  tables: { todos, autoTodos },
  collectionMetas: {
    todos: { table: 'todos', primaryKeys: ['id'] },
    // A table whose primary key is generated by the database, so the body
    // never carries it.
    autoTodos: { table: 'autoTodos', primaryKeys: ['id'] },
  },
  collectionRelations: {},
  useDrizzles: { default: () => db },
}))

const { drizzleCreate } = await import('../src/runtime/server/utils/operations/create')

function create(collection: string, body: Record<string, any>) {
  return drizzleCreate({
    event: {} as any,
    collection,
    params: { collection },
    query: {},
    body,
  })
}

describe('drizzleCreate conflict handling', () => {
  beforeEach(() => {
    db = createFakeDb({})
  })

  it('throws 409 when the primary key is already taken', async () => {
    db = createFakeDb({ insertError: new Error('UNIQUE constraint failed: todos.id'), existing: [{ id: 'a' }] })
    await expect(create('todos', { id: 'a', text: 'a' })).rejects.toMatchObject({ statusCode: 409 })
  })

  // A failure on some other constraint must stay a 500 so it is retried, and
  // so the real cause is not hidden behind a misleading conflict.
  it('rethrows the original error when no row exists for the key', async () => {
    const insertError = new Error('NOT NULL constraint failed: todos.text')
    db = createFakeDb({ insertError, existing: [] })
    await expect(create('todos', { id: 'a' })).rejects.toBe(insertError)
  })

  it('does not probe when the body does not carry the primary key', async () => {
    const insertError = new Error('NOT NULL constraint failed: autoTodos.text')
    db = createFakeDb({ insertError })
    await expect(create('autoTodos', { text: 'a' })).rejects.toBe(insertError)
    expect(db.probes).toHaveLength(0)
  })

  it('rethrows the original error when the probe itself fails', async () => {
    const insertError = new Error('UNIQUE constraint failed: todos.id')
    db = createFakeDb({ insertError, probeError: new Error('connection is closed') })
    await expect(create('todos', { id: 'a' })).rejects.toBe(insertError)
  })

  // The whole point of checking after the fact rather than before is that a
  // successful create costs no extra round-trip.
  it('does not probe on a successful create', async () => {
    const result = await create('todos', { id: 'a', text: 'a' })
    expect(result).toEqual({ id: 'a', text: 'a' })
    expect(db.probes).toHaveLength(0)
  })
})
