import { SQLiteSyncDialect, sqliteTable, text } from 'drizzle-orm/sqlite-core'
import { beforeEach, describe, expect, it, vi } from 'vitest'

const todos = sqliteTable('todos', {
  id: text('id').primaryKey(),
  text: text('text'),
})

const autoTodos = sqliteTable('autoTodos', {
  id: text('id').primaryKey(),
  text: text('text'),
})

interface FakeDbOptions {
  /** Error the insert rejects with, if any. */
  insertError?: unknown
  /** Rows the existence probe finds. */
  existing?: any[]
  /** Error the existence probe rejects with, if any. */
  probeError?: unknown
  /** Complete row returned by the database after inserting. */
  inserted?: Record<string, unknown>
}

/**
 * Minimal stand-in for a drizzle database exposing only the two chains
 * `drizzleCreate` walks: `insert().values().returning()` and
 * `select().from().where().limit()`. Records inputs independently of its
 * canned results, so empty writes or wrong-key probes cannot claim success.
 */
function createFakeDb({ insertError, existing = [], probeError, inserted = { id: 'a', text: 'a' } }: FakeDbOptions) {
  const probes: any[] = []
  const writes: Array<{ table: unknown, body: unknown }> = []
  return {
    probes,
    writes,
    insert: (table: unknown) => ({
      values: (body: unknown) => {
        // Snapshot the payload at the DB boundary, before later caller changes.
        writes.push({ table, body: structuredClone(body) })
        return {
          returning: () => insertError ? Promise.reject(insertError) : Promise.resolve([inserted]),
        }
      },
    }),
    select: () => ({
      from: (table: unknown) => ({
        where: (condition: any) => {
          return {
            limit: (limit: number) => {
              probes.push({ table, condition, limit })
              return probeError ? Promise.reject(probeError) : Promise.resolve(existing)
            },
          }
        },
      }),
    }),
  }
}

let db: ReturnType<typeof createFakeDb>

vi.mock('$rstore-drizzle-server-utils.js', () => ({
  dialect: 'sqlite',
  tables: { todos, autoTodos },
  collectionMetas: {
    todos: { table: 'todos', primaryKeys: ['id'] },
    // A table whose primary key is generated by the database, so the body
    // never carries it.
    autoTodos: { table: 'autoTodos', primaryKeys: ['id'] },
  },
  collectionRelations: {},
  useDrizzles: { default: () => db },
}))

const { drizzleCreate } = await import('../src/runtime/server/utils/operations/create')

/** Executes the production create adapter with a client-authored body. */
function create(collection: string, body: Record<string, any>) {
  return drizzleCreate({
    event: {} as any,
    collection,
    params: { collection },
    query: {},
    body,
  })
}

describe('drizzleCreate conflict handling', () => {
  beforeEach(() => {
    db = createFakeDb({})
  })

  it('probes the requested primary key before reporting a duplicate', async () => {
    db = createFakeDb({ insertError: new Error('UNIQUE constraint failed: todos.id'), existing: [{ id: 'a' }] })
    const body = { id: 'a', text: 'Different title' }
    await expect(create('todos', body)).rejects.toMatchObject({ statusCode: 409 })
    expect(body).toEqual({ id: 'a', text: 'Different title' })
    expect(db.writes).toEqual([{ table: todos, body: { id: 'a', text: 'Different title' } }])
    expect(db.probes).toHaveLength(1)
    expect(db.probes[0].table).toBe(todos)
    expect(db.probes[0].limit).toBe(1)
    const { sql, params } = new SQLiteSyncDialect().sqlToQuery(db.probes[0].condition)
    expect(sql).toBe('"todos"."id" = ?')
    expect(params).toEqual(['a'])
  })

  // A failure on some other constraint must stay a 500 so it is retried, and
  // so the real cause is not hidden behind a misleading conflict.
  it('rethrows the original error when no row exists for the key', async () => {
    const insertError = new Error('NOT NULL constraint failed: todos.text')
    db = createFakeDb({ insertError, existing: [] })
    await expect(create('todos', { id: 'a' })).rejects.toBe(insertError)
  })

  it('does not probe when the body does not carry the primary key', async () => {
    const insertError = new Error('NOT NULL constraint failed: autoTodos.text')
    db = createFakeDb({ insertError })
    await expect(create('autoTodos', { text: 'a' })).rejects.toBe(insertError)
    expect(db.probes).toHaveLength(0)
  })

  it('rethrows the original error when the probe itself fails', async () => {
    const insertError = new Error('UNIQUE constraint failed: todos.id')
    db = createFakeDb({ insertError, probeError: new Error('connection is closed') })
    await expect(create('todos', { id: 'a' })).rejects.toBe(insertError)
  })

  // The whole point of checking after the fact rather than before is that a
  // successful create costs no extra round-trip.
  it('writes the client body and returns database fields without probing', async () => {
    const body = { id: 'created-42', text: 'Client title' }
    const inserted = { id: 'created-42', text: 'Client title', createdAt: new Date('2026-01-02T03:04:05Z') }
    db = createFakeDb({ inserted })
    const result = await create('todos', body)
    expect(result).toEqual({ id: 'created-42', text: 'Client title', createdAt: new Date('2026-01-02T03:04:05Z') })
    expect(body).toEqual({ id: 'created-42', text: 'Client title' })
    expect(db.writes).toEqual([{ table: todos, body: { id: 'created-42', text: 'Client title' } }])
    expect(db.probes).toHaveLength(0)
  })
})
