import type { DirectusCollection, DirectusField, DirectusRelation } from '@directus/sdk'
import type { Collection } from '@rstore/shared'

/**
 * Options used to transform Directus system metadata into rstore collections.
 */
export interface BuildDirectusCollectionsOptions {
  /**
   * Directus collections returned by `readCollections()`.
   */
  collections: DirectusCollection[]

  /**
   * Directus fields grouped by collection name.
   */
  fields: Map<string, DirectusField[]>

  /**
   * Directus relations returned by `readRelations()`.
   */
  relations: DirectusRelation[]

  /**
   * rstore plugin scope id assigned to generated collections.
   */
  scopeId: string
}

/**
 * Directus metadata stored on generated rstore collections.
 */
export interface GeneratedDirectusMeta {
  /**
   * Primary key field names discovered from Directus field schemas.
   */
  primaryKeys: string[]

  /**
   * Directus-specific collection metadata.
   */
  directus: {
    /**
     * Original Directus collection name.
     */
    collection: string

    /**
     * Whether the Directus collection is configured as a singleton.
     */
    singleton: boolean
  }
}

/**
 * rstore collection plus generated metadata used by templates.
 */
export interface DirectusCollectionDefinition extends Collection {
  /**
   * TypeScript interface name generated for the collection item.
   */
  typeName: string

  /**
   * Directus fields associated with the collection.
   */
  directusFields: DirectusField[]

  /**
   * JavaScript expression used by generated `getKey`.
   */
  getKeyExpression: string

  /**
   * Generated Directus collection metadata.
   */
  meta: GeneratedDirectusMeta

  /**
   * Generated rstore relations.
   */
  relations: NonNullable<Collection['relations']>
}

const IDENTIFIER_RE = /^[A-Z_$][\w$]*$/i

/**
 * Builds rstore collection definitions from Directus introspection metadata.
 */
export function buildDirectusCollections(
  options: BuildDirectusCollectionsOptions,
): DirectusCollectionDefinition[] {
  const definitions = options.collections
    .filter(shouldIncludeDirectusCollection)
    .map(collection => createCollectionDefinition(collection, options.fields, options.scopeId))

  const definitionsByName = new Map(definitions.map(definition => [definition.name, definition]))
  for (const relation of options.relations) {
    addAliasSideRelation(definitionsByName, options.fields, relation)
  }

  return definitions
}

/**
 * Converts a Directus field type to a generated TypeScript type.
 */
export function directusFieldToTsType(field: DirectusField): string {
  const type = directusFieldBaseTsType(field)
  return getFieldSchema(field)?.is_nullable ? `${type} | null` : type
}

/**
 * Creates a valid TypeScript interface name from a Directus collection name.
 */
export function directusCollectionTypeName(collectionName: string): string {
  const name = collectionName
    .split(/[^\w$]+/)
    .filter(Boolean)
    .map(part => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
    .join('')

  return IDENTIFIER_RE.test(name) ? name : `Directus${name || 'Item'}`
}

/**
 * Returns whether a Directus collection should be exposed to rstore.
 */
function shouldIncludeDirectusCollection(collection: DirectusCollection): boolean {
  return !!collection.schema
    && !collection.collection.startsWith('directus_')
    && !collection.meta?.hidden
}

/**
 * Creates one rstore collection definition without relations.
 */
function createCollectionDefinition(
  collection: DirectusCollection,
  fields: Map<string, DirectusField[]>,
  scopeId: string,
): DirectusCollectionDefinition {
  const directusFields = fields.get(collection.collection) ?? []
  const primaryKeys = directusFields
    .filter(field => getFieldSchema(field)?.is_primary_key)
    .map(field => field.field)

  const meta = {
    primaryKeys,
    directus: {
      collection: collection.collection,
      singleton: collection.meta?.singleton ?? false,
    },
  }

  return {
    '~type': 'collection',
    'name': collection.collection,
    'scopeId': scopeId,
    'meta': meta,
    'relations': {},
    'directusFields': directusFields,
    'typeName': directusCollectionTypeName(collection.collection),
    'getKeyExpression': createGetKeyExpression(primaryKeys, meta.directus.singleton),
  }
}

/**
 * Adds the safe one-side alias relation generated by Directus.
 */
function addAliasSideRelation(
  definitionsByName: Map<string, DirectusCollectionDefinition>,
  fields: Map<string, DirectusField[]>,
  relation: DirectusRelation,
): void {
  if (typeof relation.related_collection !== 'string') {
    return
  }

  const source = definitionsByName.get(relation.related_collection)
  const target = definitionsByName.get(relation.collection)
  const relationKey = relation.meta?.one_field
  if (!source || !target || !relationKey) {
    return
  }

  const aliasField = fields.get(source.name)?.find((field) => {
    return field.field === relationKey && field.type === 'alias' && !getFieldSchema(field)
  })
  if (!aliasField) {
    return
  }

  source.relations[relationKey] = {
    many: true,
    to: {
      [target.name]: {
        on: {
          [relation.field]: source.meta.primaryKeys[0] ?? relation.schema?.foreign_key_column ?? 'id',
        },
      },
    },
  }
}

/**
 * Creates the generated `getKey` expression body.
 */
function createGetKeyExpression(primaryKeys: string[], singleton: boolean): string {
  if (singleton) {
    return '\'singleton\''
  }
  if (!primaryKeys.length) {
    return 'item.id'
  }
  return primaryKeys
    .map(key => itemAccessExpression(key))
    .join(' + \'::\' + ')
}

/**
 * Creates a safe JavaScript item property access expression.
 */
function itemAccessExpression(key: string): string {
  return /^[A-Z_$][\w$]*$/i.test(key) ? `item.${key}` : `item[${JSON.stringify(key)}]`
}

/**
 * Returns the schema object while tolerating Directus alias fields.
 */
function getFieldSchema(field: DirectusField): DirectusField['schema'] | null {
  return (field as unknown as { schema?: DirectusField['schema'] | null }).schema ?? null
}

/**
 * Converts a Directus field type to its non-null TypeScript type.
 */
function directusFieldBaseTsType(field: DirectusField): string {
  switch (field.type.toLowerCase()) {
    case 'string':
    case 'text':
    case 'uuid':
    case 'hash':
    case 'date':
    case 'datetime':
    case 'timestamp':
    case 'time':
      return 'string'
    case 'integer':
    case 'biginteger':
    case 'float':
    case 'decimal':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'json':
      return 'any'
    default:
      return 'any'
  }
}
